### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Nickkk1124** [xiongyihui/python-webrtc-audio-processing#2]
Traceback (most recent call last):
  File "wav_ns.py", line 36, in <module>
    data_out = ap.process_stream(data)
  File "/home/amber/Desktop/env/.env/lib/python3.5/site-packages/webrtc_audio_processing/webrtc_audio_processing.py", line 82, in process_stream
    def process_stream(self, *args): return _webrtc_audio_processing.AudioProcessingModule_process_stream(self, *args)
TypeError: in method 'AudioProcessingModule_process_stream', argument 2 of type 'std::string const &'

**Comment by xiongyihui** [comment]
Maybe your `swig` is too old. Try to use the latest  swig
